---
# aqua Policy
# https://aquaproj.github.io/
registries:
- name: local
  type: local
  path: .aqua-registry.yaml
- type: standard
  ref: semver(">= 3.0.0")
packages:
- registry: local
  name: honnef.co/go/tools/cmd/staticcheck
- registry: standard
