---
# aqua Registry
# https://aquaproj.github.io/
packages:
- name: honnef.co/go/tools/cmd/staticcheck
  type: go_install
  repo_owner: dominikh
  repo_name: go-tools
  path: honnef.co/go/tools/cmd/staticcheck
  description: Go static analysis, detecting bugs, performance issues, and much more.
