---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
registries:
- type: standard
  ref: v4.324.2 # renovate: depName=aquaproj/aqua-registry
- name: local
  type: local
  path: .aqua-registry.yaml
packages:
- name: golang/go@go1.23.6
- name: honnef.co/go/tools/cmd/staticcheck@2024.1.1
  registry: local
  tags: [go]
- name: securego/gosec@v2.22.2
- name: reviewdog/reviewdog@v0.20.3
- name: mvdan/sh@v3.11.0
- name: koalaman/shellcheck@v0.10.0
- name: rhysd/actionlint@v1.7.7
- name: rust-lang/mdBook@v0.4.46
- name: takumin/gjson@v0.0.3
- name: aquasecurity/trivy@v0.60.0
- name: takumin/gyaml@v0.0.2
- name: editorconfig-checker/editorconfig-checker@v3.2.0
- name: oven-sh/bun@bun-v1.2.4
- name: k1LoW/octocov@v0.64.0
- name: google/yamlfmt@v0.16.0
- name: suzuki-shunsuke/ghalint@v1.2.3
- name: suzuki-shunsuke/pinact@v1.2.2
- name: go-task/task@v3.41.0
- name: evilmartians/lefthook@v1.11.3
