---
# https://taskfile.dev
# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  default:
    silent: true
    deps:
    - pinact

  pinact:
    run: once
    sources:
    - '.github/**/*.yml'
    - '.github/**/*.yaml'
    generates:
    - .task/.done_{{.TASK}}
    cmds:
    - pinact run
    - cmd: touch .task/.done_{{.TASK}}
      silent: true
