---
name: Setup Aqua
description: Setup Aqua by using cache and environment variables
runs:
  using: composite
  steps:
  - name: Go Vars
    id: go
    shell: bash
    run: |-
      echo GOPATH="${HOME}/.local/share/aquaproj-aqua-go" >> "$GITHUB_OUTPUT"
      echo GOCACHE="${HOME}/.local/share/aquaproj-aqua-go/bld" >> "$GITHUB_OUTPUT"
  - name: Allow Local Registry
    shell: bash
    run: echo "AQUA_POLICY_CONFIG=${{ github.workspace }}/.aqua-policy.yaml" >> "$GITHUB_ENV"
  - name: Restore Aqua Cache
    id: cache-primes-restore
    uses: actions/cache/restore@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
    with:
      key: aqua-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/.aqua.yaml') }}
      path: |-
        ~/.local/share/aquaproj-aqua
        ${{ steps.go.outputs.GOPATH }}
  - name: Setup Aqua
    uses: aquaproj/aqua-installer@e2d0136abcf70b7a2f6f505720640750557c4b33 # v3.1.1
    with:
      aqua_version: v2.43.2
      enable_aqua_install: false
  - name: Install Tools
    shell: bash
    env:
      GOPATH: ${{ steps.go.outputs.GOPATH }}
      GOCACHE: ${{ steps.go.outputs.GOCACHE }}
    run: |-
      aqua install --exclude-tags go --all
      aqua install --all
  - name: Get Default Branch
    id: gh
    env:
      GH_TOKEN: ${{ github.token }}
    shell: bash
    run: echo default_branch_ref_name="$(gh repo view --json defaultBranchRef --jq .defaultBranchRef.name)" >> "$GITHUB_OUTPUT"
  - name: Show Branch
    shell: bash
    run: |-
      echo '"${{ github.ref_name }}"'
      echo '"${{ steps.gh.outputs.default_branch_ref_name }}"'
  - name: Save Aqua Cache
    if: github.ref_name == steps.gh.outputs.default_branch_ref_name && steps.cache-primes-restore.outputs.cache-hit != 'true'
    uses: actions/cache/save@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
    with:
      key: ${{ steps.cache-primes-restore.outputs.cache-primary-key }}
      path: |-
        ~/.local/share/aquaproj-aqua
        ${{ steps.go.outputs.GOPATH }}
