---
name: CI
on:
  push:
    branches:
    - main
    tags:
    - 'v*'
  pull_request:
permissions: {}
jobs:
  ##############################################################################
  # Linter
  ##############################################################################
  linter:
    name: Linter
    permissions:
      actions: read
      checks: write
      contents: read
      pull-requests: write
    uses: ./.github/workflows/linter.yml
  ##############################################################################
  # Application
  ##############################################################################
  application:
    name: Application
    permissions:
      attestations: write
      contents: write
      id-token: write
      pull-requests: write
    uses: ./.github/workflows/application.yml
  ##############################################################################
  # Status Check
  ##############################################################################
  ci:
    needs:
    - linter
    - application
    name: CI
    runs-on: ubuntu-latest
    timeout-minutes: 3
    if: failure()
    steps:
    - name: Failure Status
      run: exit 1
  ##############################################################################
  # Timeline
  ##############################################################################
  timeline:
    needs: ci
    name: Timeline
    runs-on: ubuntu-latest
    timeout-minutes: 3
    permissions:
      actions: read
    if: always()
    steps:
    - name: Actions Timeline
      uses: Kesin11/actions-timeline@3046833d9aacfd7745c5264b7f3af851c3e2a619 # v2.2.1
