---
name: Setup Repository
on:
  push:
    branches:
    - 'main'
permissions: {}
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
    if: ${{ !startsWith(github.repository, 'takumin/boilerplate-golang-cli') }}
    steps:
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 0
        persist-credentials: false
    - name: Setup Go
      uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
      with:
        go-version-file: 'go.mod'
    - name: Setup Tools
      run: go install github.com/sirkon/go-imports-rename@latest
    - name: Setup Repository
      run: ./scripts/setup-repository.bash
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Cleanup Boilerplate
      run: |
        rm .github/workflows/setup-repository.yml
        rm scripts/setup-repository.bash
    - name: Reinitialize Repository
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |-
        git remote set-url origin "https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add .
        git commit -m 'Reinitialize commit'
        git push
